apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pvclaim
  namespace: mysql
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 0.5 Gi
