apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-pv
  namespace: mysql
  labels:
    app: mysql
spec:
  storageClassName: manual
  capacity:
    storage: 1 Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/home/ubuntu/volume"
