apiVersion: apps/v1
kind: Deployment

metadata:
  name: nginx-deployment
  namespace: nginx
  labels:
    app: nginx

spec:
  replicas: 2
  selector:
    matchLabels:
      app : nginx

  template:
    metadata:
      namespace: nginx
      labels:
        app: nginx
    spec:
      containers:
        - name: naginx
          image: nginx:latest
          ports:
          - containerPort: 80

